---
kind: pipeline
name: pipeline
type: docker

steps:
  - name: build
    image: unfor19/serverless-template:latest
    commands:
      - bash ./scripts/app_build.sh

  - name: deploy-aws-resources
    image: unfor19/serverless-template:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
      AWS_DEFAULT_REGION:
        from_secret: aws_region
    commands:
      - cd ./aws-resources
      - yarn deploy:dev
    depends_on:
      - build

  - name: deploy-todo-api-lambda-layer
    image: unfor19/serverless-template:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
      AWS_DEFAULT_REGION:
        from_secret: aws_region
    commands:
      - PROJECT_DIR="$PWD"
      - cd "$PROJECT_DIR/services/todo-api/layer" && yarn deploy:dev
    depends_on:
      - build

  - name: deploy-greet-api-lambda-layer
    image: unfor19/serverless-template:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
      AWS_DEFAULT_REGION:
        from_secret: aws_region
    commands:
      - PROJECT_DIR="$PWD"
      - cd "$PROJECT_DIR/services/greet-api/layer" && yarn deploy:dev
    depends_on:
      - build

  - name: deploy-api-lambda-layers
    image: unfor19/serverless-template:latest
    depends_on:
      - deploy-todo-api-lambda-layer
      - deploy-greet-api-lambda-layer

  - name: deploy-todo-api-functions
    image: unfor19/serverless-template:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
      AWS_DEFAULT_REGION:
        from_secret: aws_region
    commands:
      - PROJECT_DIR="$PWD"
      - cd "$PROJECT_DIR/services/todo-api" && yarn deploy:dev
    depends_on:
      - build
      - deploy-aws-resources
      - deploy-todo-api-lambda-layer

  - name: deploy-greet-api-functions
    image: unfor19/serverless-template:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
      AWS_DEFAULT_REGION:
        from_secret: aws_region
    commands:
      - PROJECT_DIR="$PWD"
      - cd "$PROJECT_DIR/services/greet-api" && yarn deploy:dev
    depends_on:
      - build
      - deploy-aws-resources
      - deploy-greet-api-lambda-layer

  - name: deploy-api-functions
    image: unfor19/serverless-template:latest
    depends_on:
      - deploy-todo-api-functions
      - deploy-greet-api-functions

  - name: usage
    image: unfor19/serverless-template:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
      AWS_DEFAULT_REGION:
        from_secret: aws_region
    commands:
      - APIGW_ID=$(bash ./scripts/get_apigw_endpoint.sh serverless-template-rest-api-dev)
      - APIGATEWAY_ENDPOINT="https://$APIGW_ID.execute-api.$AWS_REGION.amazonaws.com"
      - echo $APIGATEWAY_ENDPOINT
      - MY_CONTENT="some content"
      - RESULT=$(curl --silent --location --request POST $APIGATEWAY_ENDPOINT/dev/todo/create --header 'Content-Type:application/json' --data-raw '{ "content":"'"$MY_CONTENT"'" }')
      - echo $RESULT
      - MY_NAME="Willy"
      - RESULT=$(curl --silent --location --request GET "$APIGATEWAY_ENDPOINT/dev/greet/$MY_NAME")
      - echo $RESULT
    depends_on:
      - deploy-aws-resources
      - deploy-api-functions
      - deploy-api-lambda-layers

  - name: cleanup-todo-api-functions
    image: unfor19/serverless-template:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
      AWS_DEFAULT_REGION:
        from_secret: aws_region
    commands:
      - PROJECT_DIR="$PWD"
      - cd "$PROJECT_DIR/services/todo-api" && yarn destroy:dev
    depends_on:
      - usage

  - name: cleanup-greet-api-functions
    image: unfor19/serverless-template:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
      AWS_DEFAULT_REGION:
        from_secret: aws_region
    commands:
      - PROJECT_DIR="$PWD"
      - cd "$PROJECT_DIR/services/greet-api" && yarn destroy:dev
    depends_on:
      - usage

  - name: cleanup-api-functions
    image: unfor19/serverless-template:latest
    depends_on:
      - cleanup-todo-api-functions
      - cleanup-greet-api-functions

  - name: cleanup-todo-api-lambda-layer
    image: unfor19/serverless-template:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
      AWS_DEFAULT_REGION:
        from_secret: aws_region
    commands:
      - PROJECT_DIR="$PWD"
      - cd "$PROJECT_DIR/services/todo-api/layer" && yarn destroy:dev
    depends_on:
      - usage

  - name: cleanup-greet-api-lambda-layer
    image: unfor19/serverless-template:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
      AWS_DEFAULT_REGION:
        from_secret: aws_region
    commands:
      - PROJECT_DIR="$PWD"
      - cd "$PROJECT_DIR/services/greet-api/layer" && yarn destroy:dev
    depends_on:
      - usage

  - name: cleanup-api-lambda-layers
    image: unfor19/serverless-template:latest
    depends_on:
      - cleanup-todo-api-lambda-layer
      - cleanup-greet-api-lambda-layer

  - name: cleanup-aws-resources
    image: unfor19/serverless-template:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
      AWS_DEFAULT_REGION:
        from_secret: aws_region
    commands:
      - PROJECT_DIR="$PWD"
      - cd "$PROJECT_DIR/aws-resources" && yarn destroy:dev
    depends_on:
      - usage
      - cleanup-api-functions
